ci(coverage): Added coverage step in github action workflow

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -27,6 +27,47 @@ jobs:
 
       - name: Run tests
         run: dotnet test --no-build --verbosity normal
+  coverage:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: "8.0"
+
+      - name: Install ReportGenerator
+        run: dotnet tool install --global dotnet-reportgenerator-globaltool
+
+      - name: Restore dependencies
+        run: dotnet restore
+
+      - name: Run Tests with Coverage
+        run: dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults
+
+      - name: Merge Coverage Reports
+        run: |
+          reportgenerator -reports:TestResults/**/coverage.cobertura.xml -targetdir:CoverletReport -reporttypes:TextSummary,Cobertura
+
+      - name: Check Coverage Threshold (80% minimum)
+        run: |
+          coverage=$(grep -oP 'Line coverage:\s+\K[0-9.]+' CoverletReport/Summary.txt)
+          echo "Coverage: $coverage%"
+          if (( $(echo "$coverage < 80.0" | bc -l) )); then
+            echo "❌ Code coverage is below 80%. Failing the build."
+            exit 1
+          else
+            echo "✅ Code coverage is above 80%."
+          fi
+
+      - name: Upload Coverage Report (Optional)
+        uses: actions/upload-artifact@v4
+        with:
+          name: CoverageReport
+          path: CoverletReport
   package:
     runs-on: ubuntu-latest
     steps:
